name: Automated Cross-Platform Release

on:
  push:
    branches:
      - main

# Give the workflow permission to create and write releases
permissions:
  contents: write

jobs:
  build-and-release:
    name: Build Binaries and Create Release
    runs-on: ubuntu-latest # Runs inside a Linux cloud VM

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Go Engine
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Execute Build Script
        run: |
          chmod +x build.sh
          ./build.sh

      # Generate a unique dynamic version tag using the run number
      - name: Create and Push Git Tag
        id: create_tag # We need this ID to reference this step's outputs later
        run: |
          VERSION="v1.0.${{ github.run_number }}"

          # 1. Save the version to the step output dictionary
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Configure dummy git user
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Create and push tag
          git tag $VERSION
          git push origin $VERSION

      # Automatically bundle the binaries and publish the GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          name: Release ${{ steps.create_tag.outputs.version }}
          body: |
            Automated production build for `devops-monitor` CLI tool.

            ### Installation:
            Download the binary matching your operating system, rename it to `devops-monitor`, and add it to your system PATH.
          draft: false
          prerelease: false
          # Tell GitHub exactly which files from your /bin folder to attach to the release page
          files: |
            bin/devops-monitor-windows-amd64.exe
            bin/devops-monitor-linux-amd64
            bin/devops-monitor-darwin-amd64
            bin/devops-monitor-darwin-arm64

  publish-snap:
    name: Build and Publish Linux Snap Package
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      # 2. Compile and package your Go code into a compressed .snap file
      # This outputs a file named something like "devops-monitor_1.0.2_amd64.snap"
      - name: Build Snap Package
        run: |
          sg lxd -c "snapcraft"

      - name: Publish to Snap Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          # Using a wildcard (*) tells the action to look for the built file instead of the directory
          snap: "*.snap"
          release: stable
